### ISSUE TITLE
Bypassing timer

### ISSUE THREAD

**Issue by TristanBrotherton** [SwiCago/HarviaWiFi#11]
Hi there, I apologies for the format of this as it's not an issue with your project, but I had a question if you have the time.

I'd like to externally control the power to our KIP and bypass the timer. 

I wondered if I could ask your opinion on how to safely take the timer out of the equation so that the heater came on when power was supplied, but still used it's thermostat / limiter. 

Warm regards,

Tristan

**Comment by SwiCago** [comment]
Hi @TristanBrotherton , yes this can be done.
You would swap the timer out with a heavy duty toggle switch.
There are three wires going to the timer. The two in the left side of the timer on the diagram(also next to each other on physical device) would be connected to the toggle switch. The 3rd wire on the right side of timer on the diagram would be disconnected and wrapped in electrical tape. It would not be connected to anything.
Make sure to disconnect power before doing mods.
Green = toggle switch
Red = disconnected and wrapped
![20210803_201913](https://user-images.githubusercontent.com/24993276/128106783-fb7f20a1-b365-41b8-ac0f-5024b49c398e.png)

**Comment by TristanBrotherton** [comment]
I really appreciate your response - thank you. I intend to keep a timer, just external to the sauna so it can be toggled on remotely. Whilst taking my time to implement your solution. Thank you again!

**Comment by aypodf** [comment]
Hi, thank you so much for putting this useful project together! I'm also interested in this alternative, is there a particular heavy-duty toggle switch you would recommend. Presumably the amp rating should match the heater, right?

Thanks again!

**Comment by SwiCago** [comment]
@aypodf any standard automotive or home switch will work. The main current goes through the giant relay/contactor. The timer/limiter themselves do not feed much current to turn that giant relay/contactor on/off.

**Comment by MitchBogart** [comment]
For a Finlandia 240vac 6kw sauna with built-in controls, and similar FH72 timer, 
I am doing just that, but by using a DPDT toggle switch (On - On type), to be mounted on the bottom panel of the sauna heater, one switch functions to quickly switch between:
1) Normal mode (1hr On plus up to 8hrs of On delay); and 
2) Full bypass mode ("always" On, regardless of timer knob position, which has the motor de-energized in this position).

For easier control, I've added a "2 Pole 40 Amp contactor 120v coil 2 pole Lighting Load 50 AMP Contactor ($15.99)" controlled by a SPST wall switch with internal red light when On).  This controls full sauna power (240v) using only the smaller amount of current needed by the contactor relay coil.

I like this project so much I've also added:
a) A Shelly 1 Plus switch relay to make the SPST wall switch also remote controllable; and
b) A nice digital, easily settable wall switch countdown timer, in parallel with the SPST wall switch, so that either can turn the sauna on.

I did have to use the unused 240vac Neutral to get 120vac for this specific contactor relay and SPST switch with 120v Red pilot light. 

The sauna is in a studio structure, separate from the house.  The sauna is usually left in Full bypass mode. Operation is like this:

The Shelly app lets one turn on the sauna manually, or at a set time, from the house, allowing the sauna to get to temperature (~30min) before one (or many) goes there (in the cold).
Then, at the sauna, one [optionally] sets the number of hours, minutes of desired sauna operation on the countdown timer, closes the setting door of the timer, which starts it, and then flicks the lighted toggle switch Off.  I chose this particular timer since it has the feature that when one flips down the timer cover, one sees the remaining time left, and/or can change it.

You get: 
Remote and local control, manual or scheduled.
Optional retro (built-in 1hr) mode, if a guest prefers it, 
Visible (pilot light) indicator of sauna power on,
Very easy, digital pushbutton setting/changing sauna duration, or On/Off override
Easy viewing of the remaining On time, and
Very low cost components total cost, all listed below.

DPDT toggle switch                                                    $4.00 
     https://www.amazon.com/TWTADE-Switches-Position-Waterproof-TEN-1321MZX/dp/B082QQP7LN/
120v coil 2 Pole 40 Amp 240vac contactor relay       $15.99
     https://www.amazon.com/dp/B088895GBY
Toggle wall switch with red illuminated On handle   $15.82
     https://www.amazon.com/dp/B000LEHNQE
Shelly 1 Plus remote control (any] switch addition    $16.49
     https://www.amazon.com/gp/product/B0965JN63Q
Wall switch digital (24hr version) Countdown timer  $25.35
     https://www.amazon.com/gp/product/B07VM9WXCH/ref=ppx_yo_dt_b_asin_title_o00_s00

Total: $77.65

Full Timer Bypass with Retro mode diagram
![Image](https://github.com/user-attachments/assets/af534f89-b6f4-4187-8980-baba435e4105)

Adding a contactor relay for low current and 120v switch control with pilot light
![Image](https://github.com/user-attachments/assets/699892e5-2682-425b-8bb3-974a71a8e99b)

**Comment by denmanbw** [comment]
Thanks @MitchBogart ! I like your setup and may consider the same set up. Do you happen to have a sketch or diagram showing how all your components work together?

**Comment by MitchBogart** [comment]
Hi  denmanbw,

Yes, glad you like it. So does my son and family in whose sauna it's all
going.  I made a rough sketch for myself.  I'm in the process of using
pictures instead of pure schematic.  The timer electronic total disable
works,  my red light toggle switch controlling the contactor works.  I
changed some of the parts and I'm making it into a color interconnect
diagram for people who don't work well with schematics.

Is the Github entry still closed?
Mitch

**Comment by denmanbw** [comment]
Hi @MitchBogart (BTW, I can’t figure out how to reply on GitHub). It does say entry closed, but I’m seeing your updates. Thanks so much for sharing with us. I’ve looked at other options, which are more costly. This sounds like a very good solution!

**Comment by MitchBogart** [comment]
Hi Denmanbw,

Glad you like it!
I finished transforming my "for me only" sketches and posted it in 3
portions.
The first shows the use of the DPDT toggle switch on bottom of sauna to
implement benign mod enable both retro mode and new full anytime control.
The second shows the use of an additional wall switch control sauna heater
control via a 120vac contactor relay controlled by the wall toggle switch
with pilot light.
The third (and so far final) one shows:
    1) The addition of the 24 hour pushbutton digital timer, with Countdown
mode in addition to the toggle switch.
    2) The addition of a Shelly 1 Plus for remote (and local) control of
sauna power via the Toggle switch and/or the Countdown Timer".

The Toggle switch and the Digital Timer switch are in parallel.  Thus,
locally either one can be used to start the sauna, but both must be off
to locally stop the sauna.
It's advised to shut off the toggle switch right after you energize the
Timer; otherwise the toggle switch will keep the sauna on even after the
timer is off.
You can always turn the sauna on and off (regardless of the toggle and
digital timer) via the remote Shelly App.

I think I can post because I am a long time member of Github.

Best regards,
Mitch

**Comment by MitchBogart** [comment]
![Image](https://github.com/user-attachments/assets/3aa31e25-81dc-4917-8a05-d211882bc73d)

![Image](https://github.com/user-attachments/assets/c7862132-2478-4349-97fc-a32a50fc5c5e)

![Image](https://github.com/user-attachments/assets/dba4cb13-d9f9-43d7-822e-be0ecbf68b9a)

**Comment by SwiCago** [comment]
@MitchBogart , @denmanbw  
Glad to see there is still some interest in this project. Hope you all enjoy your saunas as much  as I do.

**Comment by denmanbw** [comment]
This is very helpful and appreciated. Again, thank you @MitchBogart for sharing! Ive been considering something like this:

https://www.amazon.com/SURAIELEC-Electrical-Distribution-Waterproof-Decorations/dp/B0D9LCZ11S/ref=asc_df_B0D9LCZ11S?mcid=32526382a9dc3ae8beb0cbfe193558f4&hvocijid=8287843545326145009-B0D9LCZ11S-&hvexpln=73&tag=hyprod-20&linkCode=df0&hvadid=730434177080&hvpos=&hvnetw=g&hvrand=8287843545326145009&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9003445&hvtargid=pla-2281435178778&psc=1

This requires a neutral which I can pull or consider a WiFi switch not requiring a neutral. 

I like your bypass and retro modes via the toggle. I’m open to feedback but feel this simple set up would work for me . . .

**Comment by sendtoworthington** [comment]
> For a Finlandia 240vac 6kw sauna with built-in controls, and similar FH72 timer, I am doing just that, but by using a DPDT toggle switch (On - On type), to be mounted on the bottom panel of the sauna heater, one switch functions to quickly switch between:
> 
> 1. Normal mode (1hr On plus up to 8hrs of On delay); and
> 2. Full bypass mode ("always" On, regardless of timer knob position, which has the motor de-energized in this position).
> 
> For easier control, I've added a "2 Pole 40 Amp contactor 120v coil 2 pole Lighting Load 50 AMP Contactor ($15.99)" controlled by a SPST wall switch with internal red light when On). This controls full sauna power (240v) using only the smaller amount of current needed by the contactor relay coil.
> 
> I like this project so much I've also added: a) A Shelly 1 Plus switch relay to make the SPST wall switch also remote controllable; and b) A nice digital, easily settable wall switch countdown timer, in parallel with the SPST wall switch, so that either can turn the sauna on.
> 
> I did have to use the unused 240vac Neutral to get 120vac for this specific contactor relay and SPST switch with 120v Red pilot light.
> 
> The sauna is in a studio structure, separate from the house. The sauna is usually left in Full bypass mode. Operation is like this:
> 
> The Shelly app lets one turn on the sauna manually, or at a set time, from the house, allowing the sauna to get to temperature (~30min) before one (or many) goes there (in the cold). Then, at the sauna, one [optionally] sets the number of hours, minutes of desired sauna operation on the countdown timer, closes the setting door of the timer, which starts it, and then flicks the lighted toggle switch Off. I chose this particular timer since it has the feature that when one flips down the timer cover, one sees the remaining time left, and/or can change it.
> 
> You get: Remote and local control, manual or scheduled. Optional retro (built-in 1hr) mode, if a guest prefers it, Visible (pilot light) indicator of sauna power on, Very easy, digital pushbutton setting/changing sauna duration, or On/Off override Easy viewing of the remaining On time, and Very low cost components total cost, all listed below.
> 
> DPDT toggle switch $4.00 https://www.amazon.com/TWTADE-Switches-Position-Waterproof-TEN-1321MZX/dp/B082QQP7LN/ 120v coil 2 Pole 40 Amp 240vac contactor relay $15.99 https://www.amazon.com/dp/B088895GBY Toggle wall switch with red illuminated On handle $15.82 https://www.amazon.com/dp/B000LEHNQE Shelly 1 Plus remote control (any] switch addition $16.49 https://www.amazon.com/gp/product/B0965JN63Q Wall switch digital (24hr version) Countdown timer $25.35 https://www.amazon.com/gp/product/B07VM9WXCH/ref=ppx_yo_dt_b_asin_title_o00_s00
> 
> Total: $77.65
> 
> Full Timer Bypass with Retro mode diagram ![Image](https://github.com/user-attachments/assets/af534f89-b6f4-4187-8980-baba435e4105)
> 
> Adding a contactor relay for low current and 120v switch control with pilot light ![Image](https://github.com/user-attachments/assets/699892e5-2682-425b-8bb3-974a71a8e99b)

Hi! I am just coming across this - What gauge wire did you use for the timer bypass part (I am only looking to hook that up to a Lutron Caseta switch outside the sauna room). My concern is using regular wire would melt if it gets too hot!? Thanks in advance!
