### ISSUE TITLE
Fuse choice

### ISSUE THREAD

**Issue by lazy0ne** [SwiCago/HarviaWiFi#13]
Looking at your hardware solution, I had a concern.  The fuse block and fuses you used are designed for 12/24 VDC.  You are using these fuses at 240VAC.  If a fault were to occur, you may experience arcing, which will not provide the intended protection.  You probably should use a 250V fuse block and fuses.

**Comment by SwiCago** [comment]
The fuses are just dummies. They are not there to actually prtect anything, only allow for easy reversal w/o having  to solder or cut wires. 
I have ran mine in this config for the last 4 years w/o issues. If you want you could perma bridge the connections, instead of using a block/fuses. This was just a fast reversible way to do it. But thanks for your concern
