### ISSUE TITLE
16 amp sonoff with 20 amp fuse. 

### ISSUE THREAD

**Issue by james-maloney** [SwiCago/HarviaWiFi#6]
This is more of a question than an issue.

Have you had any issues using the Sonoff, is it not underrated given the 20A inputs? 

Thanks.

**Comment by Conciliator** [comment]
I also had a question about the fuse block. Those are ATM automotive fuses rated for 32V AC or DC, according to the Eaton Bussman spec sheet. How are you running 240V AC through those into the heating elements (at T1, T2 and T3) without them blowing?

**Comment by SwiCago** [comment]
@james-maloney  @Conciliator the bridge fuses going to the sonoff uses very little amperage. I bet you can do 5amp fuses for those 3 and be fine too. Two fuse to sonoff are used to feed it with 240v and the sonoff uses only milliamps. The 3rd fuse is the relay trigger to the big relay in the heater unit. It only has a few amp draw to trigger that thing.

As for the 3 going to the heating elements. Well there are 3 elements on  kib80b 8kW unit, which is 33amps on 240V. 33amp / 3 elements is 11amps per element at 240VAC

DC voltage always requires thicker wire as amps flow one way, but in AC the flow in both directions. Also a wire must be thicker, the lower the voltage for the same amperage. So in reality the 20amp fuses are way over kill and will never burn out. If you want you could just solder a bridge wire instead of use a fuse or use butt terminals and make your own bridge connectors. I only chose the fuse block as an easy way to link everything together and easy replace it/reverse it. And chose all 20amp fuses, so as 1) they are not the weak link and 2) you'd only have to buy one type. How you wire it up in the end is up to you, but I can guarantee you it is over kill and will never pop a fuse or go up in flames. Mine has been in use for 2 full seasons and have never had an issue with the block or fuses..and now I am on the third season.  
Also note Chicago gets bitter cold, so it takes at least an hour for my sauna to even get up to working temperature and then I bake for another 30m to 45m (at 15m intervals), so in total my sauna runs nearly 2hrs each day I use it, which is 3 - 4 times weekly

**Comment by Conciliator** [comment]
@SwiCago Thanks for the thorough explanation. Much appreciated!

**Comment by SwiCago** [comment]
@Conciliator  no problem...going to leave this for a few more day for @james-maloney  to get a chance to see the response and then close.

**Comment by james-maloney** [comment]
Thanks for the response, very helpful!
