### ISSUE TITLE
Integration with Home Assistant

### ISSUE THREAD

**Issue by skyej944** [SwiCago/HarviaWiFi#9]
How can I input the JSON config for MQTT Dash into Home Assistant?

Example in configuration.yaml :

platform: mqtt
    name: "On/Off"
    state_topic: "sonoff/sauna/set"  
    value_template: "{{ ??? }}"
    command_topic: "???"
    payload_on: "{\"state\":true}"
    payload_off: "{\"state\":false}"
    availability_topic: "???T"
    payload_available: "???"
    payload_not_available: "???"
    qos: 0
    retain: false
Am I anywhere in the ballpark? Please advise. 
P.S. Thanks for this set-up I have been able to use MQTT Dash to set my sauna (now I would like to do it away from home)

**Comment by SwiCago** [comment]
Hi @skyej944 , sorry I did not see this earlier. Anyhow, I do not use home assistant, but you can follow this link for more reference links and maybe you'll be able to figure it out.
https://github.com/SwiCago/HeatPump/tree/master/integrations/home-assistant.io 
Or look at an old commit someone did on m other library, before I deleted it, due to way too many questions on something I have no clue about
https://github.com/SwiCago/HeatPump/tree/cf83b6237f0d8a9185b625b93f5ee9710c84ae54/integrations/home-assistant.io
